/**
 * Tutor credentials. A tutor signs in with a username (the tutor ID, e.g. MAY) and an
 * 8-character password generated by Ms Aida. The username is the tutor's first name in
 * capital letters (PRD FR-TUT-001 prefix); the password replaces the earlier
 * `<NAME><3 digits>` access code.
 */
export const TUTOR_USERNAME_PATTERN = /^[A-Z]{2,20}$/;
export const PASSWORD_LENGTH = 8;

/** Characters without look-alikes (no 0/O, 1/l/I) so passwords are easy to read and type. */
const LOWER = 'abcdefghijkmnpqrstuvwxyz';
const UPPER = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
const DIGITS = '23456789';
export const PASSWORD_ALPHABET = LOWER + UPPER + DIGITS;

/** Usernames are case-insensitive: " may " -> MAY. */
export function normalizeUsername(input: string): string {
  return (input ?? '').replace(/\s+/g, '').toUpperCase();
}

export function isValidUsername(username: string): boolean {
  return TUTOR_USERNAME_PATTERN.test(username);
}

/** Derives the username from a tutor's name: first name, letters only, uppercase. */
export function usernameFromName(fullName: string): string {
  const first = (fullName ?? '').trim().split(/\s+/)[0] ?? '';
  return first
    .normalize('NFD')
    .replace(/[^A-Za-z]/g, '')
    .toUpperCase()
    .slice(0, 20);
}

/**
 * Generates a password of exactly PASSWORD_LENGTH characters containing at least one lower-case
 * letter, one upper-case letter and one digit. `randomInt(max)` must return a uniformly random
 * integer in [0, max) from a CSPRNG.
 */
export function generatePassword(randomInt: (max: number) => number): string {
  for (;;) {
    let out = '';
    for (let i = 0; i < PASSWORD_LENGTH; i++) out += PASSWORD_ALPHABET[randomInt(PASSWORD_ALPHABET.length)];
    if (/[a-z]/.test(out) && /[A-Z]/.test(out) && /\d/.test(out)) return out;
  }
}

export function isValidPasswordFormat(password: string): boolean {
  return password.length === PASSWORD_LENGTH && !/\s/.test(password);
}
